### ISSUE TITLE
change the soundcloud label from "playing a game" to "listening to soundcloud"

### ISSUE THREAD

**Issue by TheiLusion** [dead8309/Kizzy#107]
its kinda bugged me how yt music has that "listening to" label when soundcloud has "playing a game" label, so pls change that
![Screenshot_2022-12-23-22-50-36-76](https://user-images.githubusercontent.com/40916277/209363105-b8ec22e2-6055-4ac7-a5b2-05387d350871.jpg)
![Screenshot_2022-12-23-22-46-21-79](https://user-images.githubusercontent.com/40916277/209362790-d92968d1-44bd-47b9-b2e4-147e35155cfb.jpg)

**Comment by dead8309** [comment]
I was using the unreleased version of the app, and those features will be added in the next release.

However, if you want to access those features now, you can use the debug build from this [link](https://github.com/dead8309/Kizzy/suites/10031116756/artifacts/487717530).

If you plan to use the debug APK, you'll need to go to ```Settings > RPC Settings > Custom Activity Type``` and choose either "Listening" or "Watching." This will only work for experimental and media RPCs.

**Comment by dead8309** [comment]
Added in [4.1](https://github.com/dead8309/Kizzy/releases/tag/4.1)
