### ISSUE TITLE
Restarting Kizzy clears the fields in custom RPC

### ISSUE THREAD

**Issue by Soham52** [dead8309/Kizzy#108]
After closing the app when it's reopened the fields in Custom RPC get reset.

1. Open Kizzy and go to custom RPC 
2. Load a config or fill the fields
3. Restart Kizzy 
4. Now, on going to custom RPC all the fields are reset

Expected behavior
I would want the values of the last loaded config to be still there, even after restarting Kizzy

Screenshots
Before restart
![SmartSelect_20221231-092925_Kizzy.jpg](https://user-images.githubusercontent.com/73898737/210124214-402ea55e-0f27-4e08-be29-65b770b57c0a.jpg)
After restart
![SmartSelect_20221231-092958_Kizzy.jpg](https://user-images.githubusercontent.com/73898737/210124221-645cd320-e515-4f50-b2ad-a0f20dc226a7.jpg)

 - Device: Samsung M31s
 - OS: Android 12
 - Kizzy Version [4.0]

**Additional context**
Although I can just reload the config by saving it, It would be better if the configs would just stay.

**Comment by dead8309** [comment]
You can turn on custom rpc from the home screen to always enable the last run rpc.

**Comment by Soham52** [comment]
> You can turn on custom rpc from the home screen to always enable the last run rpc.

Can you please elaborate?

**Comment by dead8309** [comment]
This option 
![Example](https://user-images.githubusercontent.com/68665948/210153634-87c486fe-d8f9-4349-a3b4-e36f19850973.png)

**Comment by Soham52** [comment]
> This option 
> ![Example](https://user-images.githubusercontent.com/68665948/210153634-87c486fe-d8f9-4349-a3b4-e36f19850973.png)
> 

Although it loads the last config, my issue still persists. Is that intended?
