### ISSUE TITLE
Activity Status gets off 

### ISSUE THREAD

**Issue by TitaN002** [dead8309/Kizzy#11]
**Custom status gets off automatically after some time**

It's a huge problem. Whenever I set custom status after  few minutes (30-40 min around) it gets disappear even if the application is running in the **background.** **I also changed app settings from battery saver to no restriction** still nothing changed. Please fix it or tell me the solution

Device info
Redmi Note 9
Os - Android 11
Rom - Miui 12
Kizzy version - 3.2

**Comment by dead8309** [comment]
## See this
```
Xiaomi and their Android customization called MIUI belongs in the most
troubled group on the market with respect to non-standard background 
process limitations and non-standard permissions. There are no APIs and
no documentation for those extensions. In default settings, background
processing simply does not work right and apps using them will break.
```
from https://dontkillmyapp.com/xiaomi

**Comment by TitaN002** [comment]
Ohh ok
