### ISSUE TITLE
Should be a status without Rich presence

### ISSUE THREAD

**Issue by Gulmoul991** [dead8309/Kizzy#111]
Please add a feature which allows you to set status without forcing it to be as rich presence as im unable to see timer and for console please suggest adding playstation and xbox statuses 

Other than that this is a wonderful project and thanks for your work

**Comment by dead8309** [comment]
I'm glad you liked the project.

>Please add a feature which allows you to set status without forcing it to be as rich presence as im unable to see timer

What do you mean by `timer`? The timestamps ?

> suggest adding playstation and xbox statuses

I don't have ps games data.If you could provide any repository which have those data I would add them
