### ISSUE TITLE
Media RPC should display image from notification 

### ISSUE THREAD

**Issue by PranavPurwar** [dead8309/Kizzy#115]
**Is your feature request related to a problem? Please describe.**
I noticed that the app doesn't properly show music preview image in discord, rather just the app name. If the app really uses notifications for detecting music, it should also upload the image. Btw, I'm requesting this for non-spotify users for ex i use innertune. It would be really cool to have this.

**Comment by dead8309** [comment]
> If the app really uses notifications for detecting music, it should also upload the image. 

It does that exactly through an api call.

You can check how the app sets large image for media rpc here 
[the-large-image-in-the-rpc-is-determined-as-follows](
https://kizzydocs.vercel.app/rpc/media#the-large-image-in-the-rpc-is-determined-as-follows)

**Comment by PranavPurwar** [comment]
the app does set the MediaMetadata#METADATA_KEY_ART, not sure why it still shows app icon. 
![Screenshot_2023-01-28-22-19-57-263_com chrome canary](https://user-images.githubusercontent.com/75154889/215278971-1c562382-d170-43a7-97e6-6efca8dcb06e.jpg)

**Comment by dead8309** [comment]
Can you send me that app link ,I'll check if that's the case with me too

**Comment by PranavPurwar** [comment]
Its here: https://github.com/z-huang/InnerTune

**Comment by dead8309** [comment]
Looks like that app is only adding album name and year in MediaMetadata and not **#METADATA_KEY_ALBUM_ART** which is **detected** by Kizzy

**Comment by PranavPurwar** [comment]
okay cool, I'll contact the app dev about it
