### ISSUE TITLE
HTTP 503 Service unavailable 

### ISSUE THREAD

**Issue by Darknessy0** [dead8309/Kizzy#133]
I'm trying to customize my rpc, and the following message appears "HTTP 503 Service unavailable". If you see this I ask you to fix it, the app is fantastic and I had future plans with it, but anyway, thanks.
![IMG_20230304_153343](https://user-images.githubusercontent.com/126981522/222923110-cb251369-cc07-4c81-9479-7f38e79370f2.jpg)

**Comment by dead8309** [comment]
Should be fixed by now
