### ISSUE TITLE
Listening From Symfonium Not Showing Cover

### ISSUE THREAD

**Issue by JaxzKyd** [dead8309/Kizzy#134]
**Describe the bug**
So one of the apps I use for music listening is Symfonium (https://play.google.com/store/apps/details?id=app.symfonik.music.player)
But when trying to play music from one of the apps the rich presence shows up without a cover like this
![image](https://i.imgur.com/v2n3Qsq.png)

**To Reproduce**
1. Enable Media RPC
2. Download Symfonium
3. Add a media provider (easiest in this case would be local files)
4. Play a song

**Expected behavior**
I expected the app to show a status with a cover like it does with other music apps (Revanced Music example below) 
![image](https://i.imgur.com/EAjq8KU.png)

**Please complete the following information:**
 - Device: Samsung S21 Ultra
 - OS: Android 13
 - Kizzy Version 4.3

**Comment by dead8309** [comment]
A possible reason could be Symfonium is not providing #METADATA_KEY_ALBUM_ART which is detected by Kizzy

**Comment by JaxzKyd** [comment]
The dev for Symfonium takes feature requests. Is there specific phrasing I need to use for this?

**Comment by dead8309** [comment]
Yes , you can tell them to also add **#METADATA_KEY_ALBUM_ART** field to metadata builder

**Comment by JaxzKyd** [comment]
Followup question before I do that, I just now noticed that Oto Music also has that same issue. So is there chance for any cover workaround in Kizzy itself so multiple different apps don't need to add this?

**Comment by dead8309** [comment]
> So is there chance for any cover workaround in Kizzy itself 

The cover workaround is using the app icon.


> multiple different apps don't need to add this?

That's the bare minimum metadata every offical music players have

**Comment by JaxzKyd** [comment]
> The cover workaround is using the app icon.

I meant a different way of gathering the cover. For example, TIDAL doesn't have this field either
![image](https://i.imgur.io/5bZ8Vbr_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

However, one of my other apps KLWP can easily see the cover for it

![image] (https://i.imgur.io/DBfBVcb_d.webp?maxwidth=640&shape=thumb&fidelity=medium)
![image](https://i.imgur.io/NGi2gUv_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

> That's the bare minimum metadata every offical music players have

Also like I said before, from my testing TIDAL didn't have this either and TIDAL is pretty popular, but I digress. I still reached out to the dev of Symfonium

**Comment by Tolriq** [comment]
Many apps prefers ```METADATA_KEY_ART``` as it works in much more cases than ```METADATA_KEY_ALBUM_ART ``` and due to the nature of the bundle and their limits nearly apps can't provide both at high quality.

**Comment by dead8309** [comment]
> Many apps prefers `METADATA_KEY_ART` as it works in much more cases than `METADATA_KEY_ALBUM_ART ` and due to the nature of the bundle and their limits nearly apps can't provide both at high quality.

When I was making the media rpc i tried with bunch of different metadata keys and the ones which were able to successfully get the most results were added in the app, ok I'll try to add more ways to get art cover.

**Comment by dead8309** [comment]
Could you please confirm if the developers of Symfonium of Tidal use `MediaMetadata#METADATA_KEY_ART_URI` for images, @JaxzKyd?

**Comment by JaxzKyd** [comment]
How do I go about confirming this?

**Comment by Tolriq** [comment]
METADATA_KEY_ART and METADATA_KEY_ALBUM_ART  are the 2 more common usually you should see if the first is present then use the other.

All the _URI or _ICON could be content uri, http uri and will be more complex to handle.

**Comment by dead8309** [comment]
> All the _URI or _ICON could be content uri, http uri and will be more complex to handle.

I mean if we are getting album cover by any means then why not get the highest resolution of image possible 😄

**Comment by Tolriq** [comment]
Yes you can, would be nice, but need to handle much more case and format and too large with memory issues ;) (I'm Symfonium author BTW).

**Comment by dead8309** [comment]
I have made some adjustments to include the detection of METADATA_KEY_ART. However, I'm facing some difficulty testing it with Tidal and Symphonic. Tidal requires a paid subscription, and Symphonic requires a locally running server, which can be quite cumbersome🤕

**Comment by Tolriq** [comment]
Symfonium :p And no you can use it as a local player for your local music too.

**Comment by dead8309** [comment]
> Symfonium :p And no you can use it as a local player for your local music too.

I tried that too , but I didnt find a site which can give me songs with album covers

**Comment by Tolriq** [comment]
You can test with those fake files that embed arts.

[Pocket Symphony . 2007.zip](https://github.com/dead8309/Kizzy/files/10919219/Pocket.Symphony.2007.zip)

**Comment by dead8309** [comment]
Ok it works will push some changes shortly
![Screenshot_20230308-150808_Discord~2](https://user-images.githubusercontent.com/68665948/223677986-495f463e-7818-44c9-af59-3c53e38fb89d.png)

**Comment by dead8309** [comment]
Debug build or release one ?

**Comment by JaxzKyd** [comment]
Debug build

**Comment by JaxzKyd** [comment]
Very peculiar, I can't for the life of me get the Enable Artist Name toggle to work on the 4.4 debug build, but it works perfectly in 4.3, same music app.
**v4.4**
![v4.4](https://i.imgur.com/KSGWJkN.png)
**v4.3**
![v4.3](https://i.imgur.com/81dI9cM.png)
But I digress, the original issue I opened this for is now solved so imma close it :P
