### ISSUE TITLE
I can't allow storage permission 

### ISSUE THREAD

**Issue by MrYoshi8** [dead8309/Kizzy#145]
When I start the app it asks for storage permission but it says permanently denied, so I open the app settings but I can't grant access to anything

I'm on Android 13
![Screenshot_2023-04-19-07-57-06-483_com my kizzy](https://user-images.githubusercontent.com/131272888/233098068-e50b361f-77bd-4ba6-9b72-90fd94495ccf.jpg)
![Screenshot_2023-04-19-07-57-13-884_com google android permissioncontroller](https://user-images.githubusercontent.com/131272888/233098110-d6ce0cf1-f8fa-42de-9887-04c96f466e69.jpg)

**Comment by dead8309** [comment]
Use the [latest](https://github.com/dead8309/Kizzy/releases/latest) version
