### ISSUE TITLE
Landscape Scroll 

### ISSUE THREAD

**Issue by brostosjoined** [dead8309/Kizzy#188]
**Describe the bug**
When using landscape on the logging to discord page, one cant scroll down
to click the loggin button after filling the email and password.

**To Reproduce**
1. Go to 'loggin to discord'
2. Login while landscaped
3. Try scrolling down to the loggin button

**Expected behavior**
Scroll happenning and seeing the loggin button

**Screenshots**
None

**Please complete the following information:**
 - Device: [e.g. Galaxy A04e]
 - OS: [e.g. android 13]
 - Kizzy Version [4.6]

**Additional context**

**Comment by dead8309** [comment]
I'm afraid there's no fix for it as of now. i would suggest you to use portrait mode while logging in
