### ISSUE TITLE
MediaRPC Keeps Crashing

### ISSUE THREAD

**Issue by SantiYea** [dead8309/Kizzy#19]
Ok so, when I activate it, the app automatically crash

https://user-images.githubusercontent.com/95106797/191058329-566a2788-8e54-4a9d-92ac-f32f73b23bb5.mp4

 - Device: [Samsung A02]
 - OS: [android 11]
 - Kizzy Version [3.3]

**Comment by dead8309** [comment]
Have you given `Notification Permission` ?

**Comment by SantiYea** [comment]
> Have you given `Notification Permission` ?

Yes, all is activated 

![Screenshot_20220919-175451_Settings](https://user-images.githubusercontent.com/95106797/191114925-9397fbab-34f1-4abc-a6dd-531642bee248.jpg)

**Comment by dead8309** [comment]
Not this , i was talking about notification access

**Comment by dead8309** [comment]
Ping me in the server I'll help you out
