### ISSUE TITLE
Start Timestamp

### ISSUE THREAD

**Issue by neptalu0** [dead8309/Kizzy#193]
Is it normal for start timestamp to ignore "current" time?

Nothing shows up in the start timestamp field when I set it to "current" date and time, I somehow have to set it to another day either yesterday/tomorrow then changing it back for it to fill up the timestamp field with the "current" time in milliseconds.

Device: Redmi 9T
Kizzy Version: v5
OS: MIUI 12 Android 10

**Comment by neptalu0** [comment]
nevermind. i temporarily solved it by putting random numbers in the timestamp field first before setting a proper timestamp to current time

**Comment by dead8309** [comment]
Dates in Timestamps are not selected by default. They only appear in a circle to show what's the current date. You have to click on it to select it
