### ISSUE TITLE
RPC getting stuck

### ISSUE THREAD

**Issue by xXLaciWarriorXx** [dead8309/Kizzy#194]
Heyo

I noticed an issue with RPC breaking / getting stuck upon changing networks on my phone, and other times just randomly doing the same.
Changing networks from cell to wifi it works fine, but if i disconnect from wifi and connect back to cell, it breaks and just keeps showing the way it was last both on Discord and in notifications, making it look like i am listening to the same music for hours.

I use a Samsung Galaxy A52s 5G phone with the latest software updates, in case that plays a role in the issue.

I don't know if this is a known issue, but it didn't get fixed in the last couple of updates, so i thought i'd finally report it.

Thanks for the awesome app, have a good day. :)

**Comment by Akash-Rayy** [comment]
it could be because when you switch networks from mobile data to wifi the gateway connection detects a network change and the presence gets stopped.

**Comment by dead8309** [comment]
Currently there is only one implementation for reconnecting to discord gateway which is when discord send us reconnect op code(7). All other disconnections are treated as normal closure(which shouldn't be the case)

I'll try add retry strategy when connection goes away

**Comment by xXLaciWarriorXx** [comment]
The presence doesn't get stopped, it still reports as working correctly, just the music doesn't change in notifications or on Discord. I have to stop and start it again and then it returns to normal. 
I'd attach a video of the issue, but i am currently unable to do that sort of thing.

**Comment by dead8309** [comment]
still waiting for your video
