### ISSUE TITLE
Choose Activity Status

### ISSUE THREAD

**Issue by boudyisnoob** [dead8309/Kizzy#195]
To be able to choose activity status (online, idle, dnd) in media RPC and App Detection, small thing but it's good to have.

**Comment by dead8309** [comment]
> To be able to choose activity status (online, idle, dnd) in media RPC and App Detection, small thing but it's good to have.

Totally agree💯. 

I'm planning to have some sort of a customiser screen so people set some predefined fields for all the detection rpcs like what we have currently for `activity types and buttons`.

**Comment by dead8309** [comment]
added in https://github.com/dead8309/Kizzy/commit/92569a371a4915fafe857164a12afa626dfc7954

looks like customizer might take a while so i just added `Custom Activity Status` in Rpc Settings
