### ISSUE TITLE
Easier app Detection management

### ISSUE THREAD

**Issue by boudyisnoob** [dead8309/Kizzy#196]
**Is your feature request related to a problem? Please describe.**
- It's kinda annoying when you try to look for an app in "App Detection" it's sorted by the package name not by App name itself

**Describe the solution you'd like**
- Search Button to easily look for the apps you want.
- Shows Enabled apps first then disabled and sort them both by App name instead of pkg name.

Nothing else, I really love your work on this app and how simple it is and friendly.

**Comment by dead8309** [comment]
An update regarding this: 
- I came to a conclusion to just have **apps sorted according to their names and their checked state.**
- I feel search option is an overkill for a screen with less amount of items `(apps screen only shows user installed apps and not system ones)`. However this is a great idea and could later be added.
