### ISSUE TITLE
Spotify media bar

### ISSUE THREAD

**Issue by 023948799e213e21b53eb83785356208** [dead8309/Kizzy#199]
media rpc like spotify progress bar/time bar

**Comment by MegaSa1nt** [comment]
you cant

**Comment by 023948799e213e21b53eb83785356208** [comment]
> you cant

I only see the spotify timestamp bar in desktop app it Is possible

**Comment by MegaSa1nt** [comment]
> I only see the spotify timestamp bar in desktop app it Is possible

No, you literally cant, discord made this specifically for Spotify and therefore its not possible to do it

**Comment by 023948799e213e21b53eb83785356208** [comment]
> > I only see the spotify timestamp bar in desktop app it Is possible
> 
> No, you literally cant, discord made this specifically for Spotify and therefore its not possible to do it

Oh but how do i turn on rpc from spotify

**Comment by 023948799e213e21b53eb83785356208** [comment]
> > I only see the spotify timestamp bar in desktop app it Is possible
> 
> No, you literally cant, discord made this specifically for Spotify and therefore its not possible to do it

Or the timeline bar will reset for every song??

**Comment by MegaSa1nt** [comment]
> Oh but how do i turn on rpc from spotify

use spotify

**Comment by kelbovin** [comment]
spotify lite works too
