### ISSUE TITLE
Contribute for Translation

### ISSUE THREAD

**Issue by dead8309** [dead8309/Kizzy#2]
# Here's how you can contribute to translation

#### First get the [strings.xml](https://github.com/dead8309/Kizzy/blob/master/common/resources/src/main/res/values/strings.xml) file and [translations.xml](https://github.com/dead8309/Kizzy/blob/master/common/resources/src/main/res/values/translations.xml) files 

Make the translation in `strings.xml` and then edit `translation.xml` file fields like this :

##### Suppose you have translated to English or any other language which is already there then you have to edit the `translation.xml` file like this
```xml
<!-- Language Names Here -->
    <string-array name="languages">
        <item>English</item>
    </string-array>

<!-- Edit your name here according to translated language -->
    <string name="english_contributors">Vaibhav,Yzzik</string>
```

##### If you translated to a language which is not already there let's say `Russian` then you have to edit the `translation` file like this

```xml
<!-- Language Names Here -->
    <string-array name="languages">
        <item>English</item>
        <item>Russian</item>
    </string-array>

<!-- Edit your name here according to translated language -->
    <string name="english_contributors">Vaibhav</string>
    <string name="russian_contributors">Yzzik</string>
```

## Edit
I forgot to mention that you also have to update this field in `translation.xml` if it doesn't contain that language contributors item.

#### if you added a `new` language (let's say `russian`) then you have to edit this field as

```xml
<!-- Don't Edit this -->
    <string-array name="contributors">
        <item>@string/english_contributors</item>
        <item>@string/russian_contributors</item>
    </string-array>
```
 **Note**
You don't have to edit this field if it already contains your language item.

**Comment by Hmod977** [comment]
> # Here's how you can contribute to translation
> #### First get the [strings.xml](https://github.com/dead8309/Kizzy/blob/master/app/src/main/res/values/strings.xml) file and [translations.xml](https://github.com/dead8309/Kizzy/blob/master/app/src/main/res/values/translations.xml) files
> Make the translation in `strings.xml` and then edit `translation.xml` file fields like this :
> 
> ### Example(1)
> ##### Suppose you have translated to English or any other language which is already there then you have to edit the `translation.xml` file like this
> ```
> 
>     <string-array name="languages">
>         <item>English</item>
>     </string-array>
> 
> 
>     <string name="english_contributors">Vaibhav,Yzzik</string>
> ```
> 
> ### Example(2)
> ##### If you translated to a language which is not already there let's say `Russian` then you have to edit the `translation` file like this
> ```
> 
>     <string-array name="languages">
>         <item>English</item>
>         <item>Russian</item>
>     </string-array>
> 
> 
>     <string name="english_contributors">Vaibhav</string>
>     <string name="russian_contributors">Yzzik</string>
> ```
> 
> ## Edit
> I forgot to mention that you also have to update this field in `translation.xml` if it doesn't contain that language contributors item.
> 
> ### Example (1)
> #### if you added a `new` language (let's say `russian`) then you have to edit this field as
> ```
> 
>     <string-array name="contributors">
>         <item>@string/english_contributors</item>
>         <item>@string/russian_contributors</item>
>     </string-array>
> ```
> 
> **Note** You don't have to edit this field if it already contains your language item.
