### ISSUE TITLE
Incorrect Timestamps when playing music.

### ISSUE THREAD

**Issue by Hershey025** [dead8309/Kizzy#200]
**Describe the bug**
It doesn't show time stamp according to the song while playing music from Spotify or YT Music.

**To Reproduce**
1. Go to 'Spotify or YT Music'
2. Play any song 
3. Open Discord profile 
4. See incorrect timestamp 

**Expected behavior**
It should show time stamp according to the song. For example if the song is of 2 minutes and  I have heard 1 minute of it, then it should show timestamps according to this data.

**Please complete the following information:**
 - Device: [Xiaomi Redmi Note 9S/Pro 4g]
 - OS: [Android 12 miui 13]
 - Kizzy Version [5.1]

**Comment by dead8309** [comment]
Timestamps in media rpc are shown for how much time **has passed since enabling the media rpc**. If you want to show the timestamps for how much time it is left before this song/video ends, you would to use experimental rpc

**Comment by Hershey025** [comment]
How do I enable experimental RPC.  When I click on experimental RPC nothing happens.

**Comment by dead8309** [comment]
Its a *members-only* feature, you need to be in discord server for those features
