### ISSUE TITLE
Kizzy crashes in android 11

### ISSUE THREAD

**Issue by Kodrik90** [dead8309/Kizzy#201]
**Describe the bug**
When I open the apk, it just crashes. 

**To Reproduce**
1. Open the app
     Yeah... 

**Screenshots**
https://github.com/dead8309/Kizzy/assets/139835597/41dffc2b-6edc-47d8-a0d2-2b37d18582e3

**Please complete the following information:**
 - Device: [Huaweii HONOR X8] 
 - OS: [e.g. android 11]
 - Kizzy Version [5.1]

**Comment by Kodrik90** [comment]
Oh god, it open now dk how

**Comment by dead8309** [comment]
I'm not sure what's causing the crashing, can you confirm your android version is above 8, you have some free space available in your storage

**Comment by Kodrik90** [comment]
> I'm not sure what's causing the crashing, can you confirm your android version is above 8, you have some free space available in your storage

Yes, i have storage.
But I don't know how it works perfect on my android 9 phone (sorry for some things, its my first time on github)
