### ISSUE TITLE
rps not working 

### ISSUE THREAD

**Issue by Kvordy** [dead8309/Kizzy#204]
no rpc work on samsung helexi a12 device 4gb ram 13 android oneui version 5.1 app version 5.1

**Comment by MegaSa1nt** [comment]
send logs

**Comment by Kvordy** [comment]
> send logs

![Uploading Screenshot_20230813_202539_Kizzy.png…]()

**Comment by Kvordy** [comment]
![Screenshot_20230813_202533_Kizzy](https://github.com/dead8309/Kizzy/assets/142172132/ebf7517e-6037-4ad7-9b4b-1eacdd8e39db)
![Screenshot_20230813_202527_Kizzy](https://github.com/dead8309/Kizzy/assets/142172132/cfd54c8c-2da5-4b2a-be02-48a559e9ce83)
![Screenshot_20230813_202521_Kizzy](https://github.com/dead8309/Kizzy/assets/142172132/2f0e35aa-e160-4388-99b2-8056e4e594a9)
![Screenshot_20230813_202514_Kizzy](https://github.com/dead8309/Kizzy/assets/142172132/c91bd4b1-376c-4cf6-b4d1-ca3a4b6b6691)
![Screenshot_20230813_202507_Kizzy](https://github.com/dead8309/Kizzy/assets/142172132/e734213d-c623-40a5-ae94-98e1e24dd0d0)
![Screenshot_20230813_202500_Kizzy](https://github.com/dead8309/Kizzy/assets/142172132/a77dac2d-2e83-4e7c-9b88-4443f8000bd8)
![Screenshot_20230813_202453_Kizzy](https://github.com/dead8309/Kizzy/assets/142172132/d0f065b3-61de-4853-8591-fa03ddac923f)

**Comment by MegaSa1nt** [comment]
relogin to your account

**Comment by Kvordy** [comment]
> relogin to your account

did not help

**Comment by Kvordy** [comment]
> relogin to your account

**Comment by Kvordy** [comment]
did not help (I use a translator, so there may be errors in the text)

**Comment by dead8309** [comment]
Logout and Login again
