### ISSUE TITLE
wrong date time.

### ISSUE THREAD

**Issue by root-nate** [dead8309/Kizzy#207]
**Describe the bug**
when I put the correct date of the day (August 20), it is as if I had put the 19th.

**To Reproduce**
1. Go to Custom Rpc
2. Enter today's date (whatever day you are) 
3. Run custom rpc
4. See error. It is as if I had put the rpc as if it was yesterday
**Expected behavior**
that the date would be normal today.

**Screenshots**
![Screenshot_20230820-160510.png](https://github.com/dead8309/Kizzy/assets/110252997/ebbf1f9e-dbbf-44f3-9e3b-f65b3472d1d0![Screenshot_20230820-160525.png](https://github.com/dead8309/Kizzy/assets/110252997/c58bcc44-9cf3-461e-a50b-9f3e7c9932e9)

)
-![Screenshot_20230820-160552-683.png](https://github.com/dead8309/Kizzy/assets/110252997/4ba58603-dd30-4e87-9ea4-b17bc62b75b4)

**Please complete the following information:**
 - Device: [Moto E7 Plus]
 - OS: [Android 10]
 - Kizzy Version [5.2]

**Additional context**
Null.

**Comment by dead8309** [comment]
Sorry for replying so late, is it fixed now ?

**Comment by root-nate** [comment]
> Sorry for replying so late, is it fixed now ?

Yes, tysm
