### ISSUE TITLE
"About me" doesn't update on Kizzy

### ISSUE THREAD

**Issue by BlackusPL** [dead8309/Kizzy#21]
**Describe the bug**
If you change your "About Me" on discord, in Kizzy on profile doesn't update

**To Reproduce**
1. In discord change something in "about me"
2. Go to Kizzy app > profile

**Expected behavior**
"About me" will not been updated

**Screenshots**
![Screenshot_2022-09-21-00-25-23-92_bad2d096fd4e1d501a3d515abb245426](https://user-images.githubusercontent.com/45206560/191375841-70d094ae-73b1-4434-9b61-ecbfaf955f5a.jpg)
![Screenshot_2022-09-21-00-25-09-56_fa4ea8e8aeb69dcd3ab969e8fd3d4310](https://user-images.githubusercontent.com/45206560/191375877-fb26491d-18a2-4448-a4cb-c237ef297972.jpg)

**Informations:**
 - Device: Realme GT 5G
 - OS: Android 12
 - Kizzy Version: 3.3

**Comment by dead8309** [comment]
### This is not a Discord Client!!! 
It just stores token and only use it for rich presence
