### ISSUE TITLE
App detection RPC stops after a moment

### ISSUE THREAD

**Issue by MarioSonicLife** [dead8309/Kizzy#219]
**Describe the bug**
When using App Detection RPC, It works fine at first, but after 1~2mn, the RPC stops, but the Kizzy status in the notification bar still shows the game, even when going back to the menu, so it "froze"

**To Reproduce**
1. Select a game with App Detection RPC enabled
2. Wait a few minutes

**Expected behavior**
Keep working even after a few minutes 

**Screenshots**
![Screenshot_20230923_165748](https://github.com/dead8309/Kizzy/assets/88690199/0d9ab509-2516-4009-878d-062b57868114)
![Screenshot_20230923_165806](https://github.com/dead8309/Kizzy/assets/88690199/4606dbbd-12de-4ec7-a838-8a7dc32a5898)

**Please complete the following information:**
 - Device: Honor Pad 8 
 - OS: Android 12
 - Kizzy Version 5.2

**Comment by RedPCat** [comment]
Reproducible on Media RPC on Android 11

**Comment by dead8309** [comment]
Try disabling battery optimisation for kizzy app
