### ISSUE TITLE
Discord RPC limits from 2 to 3 minutes

### ISSUE THREAD

**Issue by PayToUse** [dead8309/Kizzy#220]
**Describe the bug**
After a day of using the app, i have a problem that makes the RPC limit from 2 to 3 minutes, I've been enjoying the app and after encountering the problem, it seemed to be temporary.

**To Reproduce**
1. Open the `Kizzy` app
2. Click on any RPC (Console RPC, App Detection, Media RPC, Custom RPC)
3. For `Console RPC`, click on any game and toggle it, while for other RPCs, do the same thing
4. Wait for 2 to 3 minutes
5. The problem encounters

**Expected behavior**
I could expect it to have and rich presence present for any longer

**Screenshots**
![Screenshot_20231003_193130](https://github.com/dead8309/Kizzy/assets/67496494/3c2b8ddd-49f0-4a74-b935-f5449c6dc896)

https://github.com/dead8309/Kizzy/assets/67496494/af06a3f0-7639-402d-b13d-992e412d6378

**Please complete the following information:**
 - Device: Huawei Nova 9 (NAM-LX9)
 - OS: EMUI 12 (Based on Android 11)
 - Kizzy Version: 3.2

**Additional context**
I could hope that this bug will be fixed in the future versions of the app, thank you!

**Comment by kyoyacchi** [comment]
did you disable battery optimization for kizzy?

**Comment by PayToUse** [comment]
no

**Comment by kyoyacchi** [comment]
> no

Then try disabling it and see if it still occurs.

**Comment by PayToUse** [comment]
instead of that, i managed the app launch manually, and it seemed to be fixed for now.

also i haven't tried that, but thanks for the help anyway
