### ISSUE TITLE
Detecting paused media

### ISSUE THREAD

**Issue by RichardKanshen** [dead8309/Kizzy#228]
**Is your feature request related to a problem? Please describe.**
The media RPC shows the current media, even if it paused.

**Describe the solution you'd like**
Show a paused icon in the place of small image in the presence.

**Describe alternatives you've considered**
Hiding the Media presence while paused altogether.

**Additional context**
N/A

**Comment by evergreen-tm** [comment]
seconding this!

**Comment by dead8309** [comment]
I think its now more difficult to do this since discord expires attachments url after some time. Sorry, I currently have no plans on adding this feature. 

Maybe if things get easier in future, i would to have this feature added
