### ISSUE TITLE
Please increase versionCode with each release

### ISSUE THREAD

**Issue by IzzySoft** [dead8309/Kizzy#229]
For at least 3 releases, `versionCode` is stuck on `5` – which means nobody who's installed your app will have received any update notification (as Android uses this to tell versions apart). So please remember to [increase `versionCode`](https://github.com/dead8309/Kizzy/blob/master/gradle/libs.versions.toml#L6) whenever you prepare a new release. Thanks in advance – also in the name of all those affected :wink:

**Comment by dead8309** [comment]
Will do from next releases. Thanks
