### ISSUE TITLE
"Listening to" instead of "Playing" when using Media Rpc

### ISSUE THREAD

**Issue by Jesto9** [dead8309/Kizzy#240]
Also would be great to add an option to remove application name and use an artists name, like instead of "Listening to (app name)" it's gonna be "Listening to (artist)", as far as my Discord app making knowlage goes, that should be an easy thing to do.

**Comment by Zyztem** [comment]
@Jesto9 In the kizzy settings, set custom activity type type to listening (2).

**Comment by Jesto9** [comment]
Yea i was a bit too quick on this report, should've looked around in settings more. I found the option but forgot about this report.
