### ISSUE TITLE
Automate Kizzy in Samsung through Routines app

### ISSUE THREAD

**Issue by ragxxv** [dead8309/Kizzy#241]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but makes the app more convenient.

**Describe the solution you'd like**
"Modes and Routines" app in Samsung devices is capable of following a protocol when conditions are met. This could allow automatic initiation of Kizzy's "Media RPC" or "App detection" when a certain targeted app or game is opened, removing the necessity to visit Kizzy first.

**Additional context**
However to do this, Kizzy would need to have the option to start RPC in it's quick access panel, so the Routines app can fetch and trigger it.

For example here the Reminder app has the create event in it's panel so it goes detected by Routines as well:
![Screenshot_20231217_211729_One UI Home](https://github.com/dead8309/Kizzy/assets/75294599/f9c6225d-5fa1-4838-96bd-061b40d61227)

![Screenshot_20231217_211441_Modes and Routines](https://github.com/dead8309/Kizzy/assets/75294599/2e6bf3ea-d50e-4a1b-8afd-d01a2621ee06)

Since Kizzy has nothing there, no event shows up on Routines to trigger.

I'm aware that a Kizzy button is also available in the notification panel which makes me think this is possible to pull off as well.
Thank you.

**Comment by dead8309** [comment]
What exactly are you trying to say, I can't understand -- pls explain further.

**Comment by ragxxv** [comment]
![Screenshot_20231217_225145_Brave](https://github.com/dead8309/Kizzy/assets/75294599/8789b4fe-c05a-4aeb-bce5-27c87a795f06)

Sure, I'm here suggesting to add these ***toggle buttons*** of "Media RPC" and "Apps RPC" in the quick access panel of Kizzy since Samsung's Routines app can ***only trigger those options***.

For example I have attached a video, the Keep Notes app has many events which I can use in Routines to start. I can customise it to make a new note whenever I open Youtube.

https://github.com/dead8309/Kizzy/assets/75294599/e71964ca-9324-42e3-924a-a71d93afcd1e

![Screenshot_20231217_223359_Modes and Routines](https://github.com/dead8309/Kizzy/assets/75294599/2b332577-41f6-4bbd-8107-7f7d05cd180c)

If you could add Apps RPC and Media RPC in that menu, users can set up the Routines app to automatically start Media RPC whenever Youtube or any other desired app is opened. I think this would be a smooth addition.

**Comment by dead8309** [comment]
Oh that, I'll try to make it. please join the discord server and @ me so I can give you the version with that added when it's done

**Comment by ragxxv** [comment]
Fantastic!

**Comment by UlyssesZh** [comment]
I would also like to see this! My use case is to automate Kizzy using MacroDroid.
