### ISSUE TITLE
Text/Code Editor Precense 

### ISSUE THREAD

**Issue by devil54a** [dead8309/Kizzy#242]
Is it possible to add a feature that auto detect if I am editing text or coding?.. I don't know how to explain but u can check this image and maybe u get it
![Screenshot_2023-11-12-22-28-51-765_com android chrome-edit](https://github.com/dead8309/Kizzy/assets/107383610/1b298ccb-42e0-40cb-a9ec-c1f877d45331)

**Comment by dead8309** [comment]
Why would you code on Android

**Comment by devil54a** [comment]
> Why would you code on Android

Why not

**Comment by MegaSa1nt** [comment]
> Why would you code on Android

No PC?

**Comment by ragxxv** [comment]
Add-ons are natively supported by VS Code. Discord RPC is one of them, and it feeds on data provided by the app itself. Is there even a stable Android coding app that can do this?

**Comment by dead8309** [comment]
None. I guess

**Comment by Wishrito** [comment]
Possibly [with Visual Studio Code remote](vscode.dev), but i think this lose interest
