### ISSUE TITLE
Some languages are missing from the `LangPrefs.kt` file

### ISSUE THREAD

**Issue by adib-yg** [dead8309/Kizzy#253]
**Describe the bug**
Some languages are missing from the `LangPrefs.kt` file
- **de** - German
- **th** - ภาษาไทย
- **ja** - 日本語

<img src="https://github.com/dead8309/Kizzy/assets/92677767/035350c6-731f-4667-b58f-76296e9881e4" width="260">

**Comment by dead8309** [comment]
Yes I have yet to add them in the prefs file

**Comment by dead8309** [comment]
added in 81cdc1fa6958ca82a548c3df94041e28ff95b785
