### ISSUE TITLE
Custom rpc doesn't display with timestamp of 000000000000 or below

### ISSUE THREAD

**Issue by R-iscool** [dead8309/Kizzy#262]
The rich presence does not display with a timestamp of 000000000000 or below

1. Go to Kizzy 
2. Make Custom RPC with timestamp of 000000000000 or below
3. Turn it on.
4. You will see no rich presence on discord 

The rich presence is supposed to show up on your profile.
![Screenshot_2024-06-01-15-31-36-405_io github pyoncord app-edit](https://github.com/dead8309/Kizzy/assets/144203241/cd32287e-f0e0-4c9a-b651-1c9f031fd74a)
![Screenshot_2024-06-01-15-31-26-308_com my kizzy](https://github.com/dead8309/Kizzy/assets/144203241/37445e13-e077-4d89-8aa9-cd927357dda8)

**Please complete the following information:**
 - Device: [Redmi 9 power]
 - OS: [android 12]
 - Kizzy Version [5.4]

**Comment by dead8309** [comment]
Discord only accepts [UNIX](https://en.m.wikipedia.org/wiki/Unix_time#:~:text=Unix%20time%20is%20a%20date,such%20as%20microseconds%20or%20nanoseconds.) Epoch time so choose the time from the calendar icon beside it

**Comment by R-iscool** [comment]
> Discord only accepts [UNIX](https://en.m.wikipedia.org/wiki/Unix_time#:~:text=Unix%20time%20is%20a%20date,such%20as%20microseconds%20or%20nanoseconds.) Epoch time so choose the time from the calendar icon beside it

Why won't the custom rpc ITSELF display if I set the time to 000000000000, instead of only the number of days not displaying?

**Comment by dead8309** [comment]
Sorry no idea why discord works that way

**Comment by R-iscool** [comment]
@dead8309 so it's a problem of discord,not kizzy?

**Comment by dead8309** [comment]
Could be, we just pass what you provide if it doesn't work it can be due to discord not accepting those values

**Comment by R-iscool** [comment]
@dead8309 ok
It's funny how the entire rpc will just not display with the input of 000000000000 timestamp
