### ISSUE TITLE
Tasker/automation tools in general support

### ISSUE THREAD

**Issue by Golem642** [dead8309/Kizzy#270]
Hello, could you please add support for automation apps ? (Tasker, Macrodroid, etc... they all use the same communication system i think)
So they can set and enable the custom status for example or modify some settings
Thanks !

**Comment by dead8309** [comment]
This is a good idea, but I'm not up for adding it right now. If you or someone else wanted to send a PR I'd be happy to review!

**Comment by Golem642** [comment]
What about modifying the settings to create a custom RPC directly from the automation app tho ?

**Comment by ImMALWARE** [comment]
This would be great feature to automatically turn on RPC when launching a game...

**Comment by dead8309** [comment]
Open to accepting prs for this, I won't be adding that by myself
