### ISSUE TITLE
Issue giving notification access

### ISSUE THREAD

**Issue by Gu57avo** [dead8309/Kizzy#273]
**Describe the bug**
When trying to give the app notification permission the system blocks the switch to enable said permission

**To Reproduce**
1. Open the app
2. Click on 'Notification Access Permission'
3. Scroll down to 'Kizzy'
4. Click on the switch
5. Get an android pop-up 

**Expected behavior**
Expected to enable the switch and give the app the permission

**Screenshots**
![Screenshot_20240724-192259.png](https://github.com/user-attachments/assets/7ed81e57-1e90-4a5e-9df0-3114acd24ad7)

https://github.com/user-attachments/assets/6ca9b551-69c8-40c7-9135-fc03fd98d02d

**Please complete the following information:**
 - Device: Moto Edge 40
 - OS: Android 13
 - Kizzy Version 5.5

**Comment by jachuu6** [comment]
Hold the Kizzy icon on home screen or either go through settings to open Kizzy app info, select three dots in top right and select "Allow Restricted Settings". It's android restriction and not a Kizzy bug.
