### ISSUE TITLE
Request for using code from this repo

### ISSUE THREAD

**Issue by z-huang** [dead8309/Kizzy#276]
Hi, I'm the developer of https://github.com/z-huang/InnerTune, an open source YouTube Music client.

I'm considering adding Discord RPC to my project. I first found https://github.com/dead8309/KizzyRPC, but this library doesn't have the ability to update information on an established connection to Discord Gateway. Each `setActivity` creates a new connection. Then, I found this repo, which has a better library. I want to reuse this library and add some modifications to fit my need. This will make my music player cooler!

I would like to kindly ask for your permission. My project is also licensed under GPL-3.0, so you can always check out my code. Also, my project has many forks. If the forks want to use your library, do they need to ask for your permission one by one, too?

Looking forward to your reply, thanks!

**Comment by ruskcoder** [comment]
Perfect!
