### ISSUE TITLE
How to fix that

### ISSUE THREAD

**Issue by Mrunknow3** [dead8309/Kizzy#278]
![Screenshot_2024-08-27-20-06-01-379_com.android.settings.jpg](https://github.com/user-attachments/assets/9b89f0c1-ec6a-4765-89b6-dc567a703f29)

**Comment by dead8309** [comment]
> *from discord server*

**Enabling Restricted Settings On MIUI Devices**

Go To Settings > Manage Apps > Select Kizzy > Scroll Up and Look For "Allow Restricted Settings" and Enable it. 👍🏻

------------------

**Enabling Restricted Settings On Android 13**

Go To Settings > Click On Apps > Select Kizzy > See Top Right Corner For Three Dots and Click on it > Allow Restricted Settings. 👍🏻
