### ISSUE TITLE
Possible Bring Back Application ID Feature?

### ISSUE THREAD

**Issue by koimoee** [dead8309/Kizzy#280]
Please bring back application Id field feature like before If Possible?, I Want to use Rich Presence from My discord Developer application Id, It's okay this application ID field feature is optional, but the most important thing is that this feature is still there.

If the application id field filled then use activity name from application id from the discord developer, if it is empty then use the custom one itself, if this is not possible at all that's okay lol, i just recommend a little.

**Comment by ThanaReka** [comment]
Hi, I'd like to try a hand at this if it's possible to implement it in the next few days.  But before I get started, I need to clarify whether I am on the right track with the idea.  Is this field to be added on the Custom RPC screen along with Activity Name, Details, etc.?

**Comment by dead8309** [comment]
You can add it under settings so all the rpc can take advantage of that. Also before sending it to discord you would need to check if it's actually valid else send the kizzy application_id present in the Constants

**Comment by dead8309** [comment]
Rough idea would be 
- Define a new Prefs key `CUSTOM_ACTIVITY_APPLICATION_ID`
- Add option for taking application id in [this screen](https://github.com/dead8309/Kizzy/blob/57920ae92b5968c8584215cf19c394ca2334e976/feature_settings/src/main/java/com/my/kizzy/feature_settings/rpc_settings/RpcSettings.kt)
- Set the application_id by accessing `Prefs.CUSTOM_ACTIVITY_APPLICATION_ID` instead of `Constants`

**Comment by ThanaReka** [comment]
Okay, I've worked out some of the logic for this in my local copy (I am guessing the application ID can be entered in a textfield within an AlertDialog on the RPC Setting screen?).  Now, to check the validity of what the user enters, we have to ensure that the entered text is an 18-digit integer?  Also, can I be assigned this issue before I continue working on it.  Thanks!
