### ISSUE TITLE
Не работает "доступ к уведомлениям" пишет в целях безопасности

### ISSUE THREAD

**Issue by Blackjacksvg** [dead8309/Kizzy#281]
Хотел добавить kizzy на новый телефон с операционной системой андройд 13 но с доступом к уведомлениям возникла ошибка хоть с другими настройками такого нет
![Screenshot_20240907-104403](https://github.com/user-attachments/assets/497dea0c-0351-4823-945d-18173fbecfe7)

**Comment by MegaSa1nt** [comment]
> > _from discord server_
> 
> **Enabling Restricted Settings On MIUI Devices**
> 
> Go To Settings > Manage Apps > Select Kizzy > Scroll Up and Look For "Allow Restricted Settings" and Enable it. 👍🏻
> 
> **Enabling Restricted Settings On Android 13**
> 
> Go To Settings > Click On Apps > Select Kizzy > See Top Right Corner For Three Dots and Click on it > Allow Restricted Settings. 👍🏻
