### ISSUE TITLE
Kizzy is not working 

### ISSUE THREAD

**Issue by melody7809** [dead8309/Kizzy#286]
After updating Kizzy it stopped working. I tried everything but it wasn't my fault. It doesn't work at all.

**Comment by Clyde6790pGIT** [comment]
Mine still works, but images on media rpc are broken, their new API is broken.

**Comment by melody7809** [comment]
Will it be fixed? :/

6 Eki 2024 Paz 16:01 tarihinde Clyde6790p‎ ***@***.***> şunu
yazdı:

**Comment by dead8309** [comment]
It's fixed in 12acbce72494fcb358b27dad63a3d1bb808012aa. Will be releasing a new version soon

**Comment by melody7809** [comment]
Thankss

6 Eki 2024 Paz 16:11 tarihinde Vaibhav Raj ***@***.***> şunu
yazdı:
