### ISSUE TITLE
Show an Album Cover

### ISSUE THREAD

**Issue by pluseach** [dead8309/Kizzy#312]
It would be great to have the option to display an album cover for playing music or videos, instead of the app icon. This would be particularly useful for players like Poweramp.  Currently, Kizzy doesn't seem to support MX Player.

**Comment by dead8309** [comment]
It displays album cover if it finds one. 
> Currently, Kizzy doesn't seem to support MX Player.

They don't share metadata most probably.

**Comment by kyrie25** [comment]
> This would be particularly useful for players like Poweramp.

Poweramp works just fine with current version.
![image](https://github.com/user-attachments/assets/a55f40dc-3c6d-4c2d-9736-6bdda990f836)

**Comment by pluseach** [comment]
> > This would be particularly useful for players like Poweramp.
> 
> Poweramp works just fine with current version on my side. ![image](https://private-user-images.githubusercontent.com/77577746/380055358-a55f40dc-3c6d-4c2d-9736-6bdda990f836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjI3MjYsIm5iZiI6MTcyOTg2MjQyNiwicGF0aCI6Ii83NzU3Nzc0Ni8zODAwNTUzNTgtYTU1ZjQwZGMtM2M2ZC00YzJkLTk3MzYtNmJkZGE5OTBmODM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEzMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZjQzZTM3ZTQ1NjM4YmU4YTcwNzFmZjI3YTBmZGExYjEzODM2Y2Y1ZTk2NjhmYWQ4ZTY0YTBkZDBlNDM5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1b5h9JCQQwWG2z_9vtthdzE-ZxaE2P-23sKgyy8Ske8)

wow how, it's now showing an album on my end tho?

**Comment by kyrie25** [comment]
> wow how, it's now showing an album on my end tho?

Probably something with the server/internet/the app at the time.
Regardless, it's already feature and you probably experienced a glitch.

**Comment by pluseach** [comment]
![Screenshot_20241025-202402_Discord~2](https://github.com/user-attachments/assets/8d96b91e-45e3-4fbc-9ed0-2c1ee585b930)

**Comment by pluseach** [comment]
can you show me the setting of your poweramp at album art setting page? it think there might be something that can fix that... @kyrie25

**Comment by kyrie25** [comment]
> can you show me the setting of your poweramp at album art setting page?

I don't think Github is the place for that nor is it relevant to the issue anymore.
Feel free to @ me in the support Discord server if you want to.

**Comment by pluseach** [comment]
alright 

> > can you show me the setting of your poweramp at album art setting page?
> 
> I don't think Github is the place for that nor is it relevant to the issue anymore. Feel free to @ me in the support Discord server if you want to.

alright sorry, and thank you.. what's your discord id btw?
i will close this issues.

**Comment by kyrie25** [comment]
> alright sorry, and thank you.. what's your discord id btw?
> i will close this issues.

`meduka_meguca`, you can double-check on my Github profile.
