### ISSUE TITLE
Sometimes custom rpc ends, is there a way that it can't end?

### ISSUE THREAD

**Issue by Redtinplac** [dead8309/Kizzy#45]
**Describe the bug**
Sometimes custom rpc ends, is there a way that it can't end?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Device: [a51]
 - OS: [android 12]
 - Kizzy Version [3.4]

**Additional context**

**Comment by dead8309** [comment]
Don't open multiple issues

**Comment by Redtinplac** [comment]
> Don't open multiple issues

What do you mean, don't open multiple issues??

**Comment by BlackusPL** [comment]
> > Don't open multiple issues
> 
> What do you mean, don't open multiple issues??

You create issue [#44](https://github.com/dead8309/Kizzy/issues/44) and after that this
