### ISSUE TITLE
Timestamps doesn't work on Media RPC

### ISSUE THREAD

**Issue by Likver** [dead8309/Kizzy#53]
I just enable the "Enable Timestamps" and it just wont show anything.

![Screenshot_20221012-002735_cropped](https://user-images.githubusercontent.com/79934166/195210314-e11d3733-30e5-4e47-9281-ac021945e564.png)
![Screenshot_20221012-003110_cropped](https://user-images.githubusercontent.com/79934166/195210316-a8b58867-1f9d-40fd-b1b0-6fde3be6e292.png)

**Please complete the following information:**
 - Device: [Xperia L3]
 - OS: [Android 8.1.0]
 - Kizzy Version [3.5]

It was working on a version, i believe it was like 2.9 or so (i dont remember correctly rn sorry) and since i updated to 3.2 (iirc) it wont work

**Comment by dead8309** [comment]
You have to restart media rpc to apply changes

**Comment by Likver** [comment]
So, i did that several times and it works now (for some reason it wasnt working before) i feel kinda dumb lol, thanks anyways
