### ISSUE TITLE
The Nintendo Rpc with kizzy crashing and custom Rpc

### ISSUE THREAD

**Issue by Tavey789** [dead8309/Kizzy#57]
the Custom Rpc enable switch Is taking forever To turn on I tap on it for a few times and the service enable won't pop up the status pls fix it and the Nintendo Rpc cause it's making it crash

**Comment by dead8309** [comment]
Are you on the latest version(3.6) ?

**Comment by Tavey789** [comment]
Yes

**Comment by Tavey789** [comment]
and Can u unbanned me I learned my lesson

**Comment by Tavey789** [comment]
wait no

**Comment by Tavey789** [comment]
it's 3.2 I haven't use this in a while

**Comment by dead8309** [comment]
> and Can u unbanned me I learned my lesson

What's your username ?

> it's 3.2 I haven't use this in a while

Always make sure that you are on latest version

**Comment by Tavey789** [comment]
Tavey789#3244

**Comment by Tavey789** [comment]
got it now 3.6

**Comment by Tavey789** [comment]
hello

**Comment by dead8309** [comment]
I have removed the ban

**Comment by Tavey789** [comment]
ok
