### ISSUE TITLE
Icon Bug Media Rpc

### ISSUE THREAD

**Issue by Sury4aa** [dead8309/Kizzy#60]
how to fix this?
![Screenshot_2022-10-16-19-57-36-143-edit_com discord](https://user-images.githubusercontent.com/115933068/196037406-dd51a21e-2941-4aaa-a599-0276531167a5.jpg)

**Comment by dead8309** [comment]
Read the message in announcement channel in my server.

**Comment by dead8309** [comment]
> I find this a little inaccessible. Not everyone has Discord

This was some context in discord about why this was happening and what was the temporary fix. The updated apk was released some hours later on GitHub too
