### ISSUE TITLE
Configs didn't shows when exists

### ISSUE THREAD

**Issue by BlackusPL** [dead8309/Kizzy#61]
Add button to check if any config exists

![Screenshot_2022-10-17-01-07-57-93_bad2d096fd4e1d501a3d515abb245426.jpg](https://user-images.githubusercontent.com/45206560/196062884-7e8efd87-957c-4af7-874a-c7f5f07b0cc1.jpg)
![Screenshot_2022-10-17-01-08-06-92_83ceefc07bf7d3f049298861e11860bc.jpg](https://user-images.githubusercontent.com/45206560/196062887-91826c01-304b-4ec2-8b52-33a30ed15e97.jpg)

**Comment by dead8309** [comment]
Is there any way I reproduce this?
App uses this simple method to filter all files which ends with `.json` so i dont think any files should be left out
https://github.com/dead8309/Kizzy/blob/18e6087b60a0422d21d83161cce3bac8016514e3/app/src/main/java/com/my/kizzy/ui/screen/custom/Menu.kt#L27-L28
