### ISSUE TITLE
Wrong activity type

### ISSUE THREAD

**Issue by NightNutSky** [dead8309/Kizzy#62]
Isn't it supposed to be "Playing"?
I don't think my memory is failing me, but activity type used to be "Playing".
![Screenshot_20221019-013536~2](https://user-images.githubusercontent.com/70456337/196558459-e8aaef10-b3a9-49e0-8fab-03078f1dc041.png)

**Comment by NightNutSky** [comment]
Same thing with Media RPC.
![Screenshot_20221019-014425~2](https://user-images.githubusercontent.com/70456337/196559102-8a0c59af-5bab-45ed-99bb-f88e496f5a5f.png)

**Comment by dead8309** [comment]
What is that?

**Comment by NightNutSky** [comment]
> What is that?

These are screenshots of my discord activity.
The first one is the App Detection,
The second one is Media RPC.

I sent it this way (screenshot of one of site integration) as discord is having issues and is currently displaying "Playing" instead of "Streaming". Therefore, this can be misleading. 

But the integration correctly reads my activity, and as you can see, we actually Streaming apps with App Detection or Media RPC enabled instead of Playing them.

**Comment by dead8309** [comment]
Then ask in their support.Its not related to my app
