### ISSUE TITLE
How to create your own rpc app

### ISSUE THREAD

**Issue by Tavey789** [dead8309/Kizzy#63]
No issue I wanna know how u create your own rpc app

**Comment by dead8309** [comment]
Read the repo

**Comment by Tavey789** [comment]
what repo

**Comment by dead8309** [comment]
> what repo

This is repository (repo) read the codes to understand how the app works then you can also create one 
## OR
You can also use [KizzyRPC](https://github.com/dead8309/KizzyRPC) library

**Comment by Tavey789** [comment]
make a video tutrioal on youtube

**Comment by Tavey789** [comment]
hello make a tutorial video
