### ISSUE TITLE
leaving rpc

### ISSUE THREAD

**Issue by ryandonq** [dead8309/Kizzy#66]
**Describe the bug**
This happens in all versions of the app

**To Reproduce**
Leave the app screen for a certain time;

**Expected behavior**

**Screenshots**
There's no way to print this error I'm saying

**Please complete the following information:**
 - Device: [Moto e(7) plus]
 - OS: [e.g. android 12]
 - Kizzy Version [3.7]

**Additional context**
First, I add the rpc normally, when I leave the screen, it runs normally, but when a certain time passes, the rpc leaves discord, I've done everything to fix it, thinking it's something
2nd plan, but it's not, I'd like you to fix that, because it's coming out every 1 hour or 40 minutes!

**Comment by dead8309** [comment]
Maybe the rpc cannot reconnect in time. I'll look into it
