### ISSUE TITLE
Unable to log in within the app

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [dead8309/Kizzy#71]
**Describe the bug**
For some reason, trying to log in to my Discord account, is met with a white, blank screen, instead of a browser embed. Regardless of the network I use, or the time period I wait for, it doesn't change. VPN running in the background doesn't affect the app.

**To Reproduce**
Launch Kizzy, then try to log in to your Discord account in order to link it.

**Expected behavior**
A Discord login screen should appear, allowing to link the account.

**Screenshots**
![Screenshot_20221106_010002_com my kizzy](https://user-images.githubusercontent.com/39307800/200147729-e8c5fbd7-c4d7-4ed6-b15d-bc6efb19143b.jpg)

**Please complete the following information:**
 - Device: Huawei MAR-LX1A (P30 lite series)
 - OS: Android 10
 - Kizzy Version: 3.8

**Additional context**
The device is not rooted, and some system apps like the Play Store are forcibly prevented from updating due to performance issues.
The Discord client installed is the latest Beta release dating at November 4, 2022.

**Comment by dead8309** [comment]
Try with better connection and see if it helped

**Comment by TheHopelessThrumbo** [comment]
It took a full app reinstall and a bit of waiting, but it eventually worked. We'll see if it properly updates my status, if not, I'll consider opening another issue.
