### ISSUE TITLE
App detection doesn't work

### ISSUE THREAD

**Issue by KiraiEEE** [dead8309/Kizzy#75]
i enabled app detection and gave all needed permissions to the app but there is nothing shown in my activity

also on SoundCloud it shows the app icon not the SC one even tho i enabled the option 
![IMG_20221120_174058.jpg](https://user-images.githubusercontent.com/54278089/202914400-8af672b7-a83a-42da-ba74-e04400743f2f.jpg)

hope u fix these 

and i loved the app since i use phone more than pc <333

thx 

(PS : ma phone is redmi note 9S)

**Comment by dead8309** [comment]
#### Try to use the tamplate while posting an issue or just mention the app version on which you face the issue


> i enabled app detection and gave all needed permissions to the app but there is nothing shown in my activity

Make sure you disable battery optimisation or better refer to this [site](https://dontkillmyapp.com) as per your device model

> also on SoundCloud it shows the app icon not the SC one even tho i enabled the option ![IMG_20221120_174058.jpg](https://user-images.githubusercontent.com/54278089/202914400-8af672b7-a83a-42da-ba74-e04400743f2f.jpg)

This can happen if you are not on the latest version. If you are on the latest one go to `settings > rpc settings > clear saved icons` and see if it helps

**Comment by KiraiEEE** [comment]
> #### Try to use the template while posting an issue or just mention the app version on which you face the issue
> 
> 
> > i enabled app detection and gave all needed permissions to the app but there is nothing shown in my activity
> 
> Make sure you disable battery optimisation or better refer to this [site](https://dontkillmyapp.com) as per your device model
> 
> > also on SoundCloud it shows the app icon not the SC one even tho i enabled the option ![IMG_20221120_174058.jpg](https://user-images.githubusercontent.com/54278089/202914400-8af672b7-a83a-42da-ba74-e04400743f2f.jpg)
> 
> This can happen if you are not on the latest version. If you are on the latest one go to `settings > rpc settings > clear saved icons` and see if it helps

1. no need for template if everything is clear xd we r not robots

2.i did it all but same shit happens theres no soundcloud icon and apps are not shown

**Comment by dead8309** [comment]
Ok I'll look into it
