### ISSUE TITLE
Streaming or Playing? Bug or no?

### ISSUE THREAD

**Issue by luanmatutu** [dead8309/Kizzy#78]
yes, when I choose the transmission it appears in the status that I am "playing" instead of "transmitted".

already in the other image when I open the profile it appears "live" which is correct.

![Screenshot_20221125_234850](https://user-images.githubusercontent.com/119089100/204069763-970f78b4-235d-455f-ab90-9ef9d90855f2.jpg)
![Screenshot_20221125_234912](https://user-images.githubusercontent.com/119089100/204069768-3adb7dce-ed68-4414-9596-48ed24ce444c.jpg)

**Comment by Tavey789** [comment]
that's what I said I request it that
