### ISSUE TITLE
Nintendo Rich Presence Crash

### ISSUE THREAD

**Issue by TitaN002** [dead8309/Kizzy#8]
Nintendo Rich Presence

Nintendo Rich isn't working. When I tries to open it my app gets crashed. 

My device
Redmi Note 9
Miui 12
Android 11.

**Comment by dead8309** [comment]
Have you tried the [latest version](https://github.com/dead8309/Kizzy/releases/tag/3.2) version as i have already fixed that problem

**Comment by dead8309** [comment]
I'm Closing this issue. If anyone faces the same problem , open it again.
