### ISSUE TITLE
Media rpc crash

### ISSUE THREAD

**Issue by Davicoderliner** [dead8309/Kizzy#82]
My rpc media is crashing then I'm click enable rpc media what I'm do?

**Comment by dead8309** [comment]
Any crash logs ?

**Comment by Davicoderliner** [comment]
Then I click enable rpc this crash and don't appear crash log

**Comment by dead8309** [comment]
> Then I click enable rpc this crash and don't appear crash log

Ok ,So have you granted Notification access to the app ?

**Comment by Davicoderliner** [comment]
Yes I'm enabled all
